# Generated by Django 3.2.16 on 2024-06-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0003_auto_20240627_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('seeker', 'Seeker'), ('provider', 'Provider')], max_length=20),
        ),
    ]
