# Generated by Django 3.2.16 on 2024-06-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0005_auto_20240627_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
