# Generated by Django 3.2.16 on 2025-04-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0010_auto_20250408_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
