# Generated by Django 3.2.16 on 2025-04-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0011_alter_jobseeker_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.URLField(default='https://example.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
