# Generated by Django 3.2.16 on 2025-04-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0012_auto_20250408_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='qualification',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='qualifications',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
