# Generated by Django 3.2.16 on 2025-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0013_auto_20250408_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
