# Generated by Django 3.2.16 on 2025-04-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0015_alter_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
