# Generated by Django 3.2.16 on 2025-04-09 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0017_job_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
