# Generated by Django 3.2.16 on 2025-04-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0018_jobapplication_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('interview', 'Interview Scheduled'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
