# Generated by Django 3.2.16 on 2025-04-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0020_auto_20250409_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('Mid-level', 'Mid-level'), ('Senior', 'Senior')], default='Fresher', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Contract', 'Contract')], default='Full-time', max_length=50),
        ),
    ]
