# Generated by Django 3.2.16 on 2025-04-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0021_auto_20250409_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='experience',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
