# Generated by Django 3.2.16 on 2025-04-09 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0027_savedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.MinLengthValidator(10, message='Phone number must be at least 10 digits.'), django.core.validators.RegexValidator('^\\+?\\d{10,20}$', message='Enter a valid phone number.')]),
        ),
        migrations.DeleteModel(
            name='SavedJob',
        ),
    ]
