# Generated by Django 3.2.16 on 2025-04-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0029_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='job_logos/'),
        ),
    ]
