# Generated by Django 3.2.16 on 2025-04-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0030_job_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_date_to_apply',
            field=models.DateField(blank=True, null=True),
        ),
    ]
