# Generated by Django 3.2.16 on 2025-04-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0033_jobnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobNotification',
        ),
    ]
