# Generated by Django 3.2.16 on 2025-04-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0036_delete_jobnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
