# Generated by Django 3.2.16 on 2025-04-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0037_alter_jobseeker_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='location_preferences',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
