# Generated by Django 3.2.16 on 2025-04-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0038_jobseeker_location_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_seen_by_provider',
            field=models.BooleanField(default=False),
        ),
    ]
