# Generated by Django 3.2.16 on 2025-04-11 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0039_jobapplication_is_seen_by_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprovider',
            name='logo',
        ),
    ]
