# Generated by Django 3.2.16 on 2025-04-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0040_remove_jobprovider_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprovider',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
