# Generated by Django 3.2.16 on 2025-04-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0041_jobprovider_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status_changed',
            field=models.BooleanField(default=False),
        ),
    ]
