# Generated by Django 3.2.16 on 2025-04-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0042_jobapplication_status_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='status_changed',
        ),
    ]
