# Generated by Django 3.2.16 on 2025-04-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0043_remove_jobapplication_status_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_seen_by_seeker',
            field=models.BooleanField(default=True),
        ),
    ]
