# Generated by Django 3.2.16 on 2025-04-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_edge', '0045_job_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprovider',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobprovider',
            name='security_question',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='security_question',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
